# Default values for chainforge-explorer
replicaCount: 2

image:
  repository: chainforge/chainforge-explorer
  tag: "0.1.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

service:
  type: ClusterIP
  apiPort: 4000
  websocketPort: 4001
  metricsPort: 8081

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: explorer.chainforge.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: chainforge-explorer-tls
      hosts:
        - explorer.chainforge.local

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

persistence:
  enabled: false

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - chainforge-explorer
        topologyKey: kubernetes.io/hostname

# ChainForge Explorer specific configuration
config:
  api:
    port: 4000
    host: "0.0.0.0"
    cors: ["*"]
    
  websocket:
    port: 4001
    host: "0.0.0.0"
    
  database:
    postgres:
      host: "chainforge-postgres"
      port: 5432
      database: "chainforge"
      user: "chainforge"
      password: "chainforge_pass"
      
  cache:
    redis:
      host: "chainforge-redis"
      port: 6379
      password: "chainforge_redis_pass"
      
  metrics:
    enabled: true
    port: 8081
    path: "/metrics"
    
  indexing:
    batchSize: 1000
    maxWorkers: 4
    backpressureLimit: 10000
